// src/components/ContactWizard.jsx
// Multi-step contact wizard: intent -> needs -> details -> WhatsApp / email handoff.
// Fully static — composes a structured brief and opens wa.me / mailto prefilled.
import { useEffect, useMemo, useState } from 'react'
import { motion, AnimatePresence } from 'motion/react'
import { BRAND, WIZARD } from '../data/site.js'
import { EASE, Magnetic } from '../lib/motion.jsx'
import { WoolButton, WoolIcon } from './Wool.jsx'

const STEPS = ['Start', 'Needs', 'Details', 'Send']
// Knit buttons carry no :disabled rule of their own — mirror what .btn:disabled did.
const WOOL_OFF = { opacity: 0.4, pointerEvents: 'none' }

// Which beat of the machine's script each step corresponds to. Kept here rather than
// in the machine so the wizard stays the single source of truth for where you are.
const STEP_STATE = ['greet', 'needs', 'details', 'review']

export function ContactWizard({ seed = null, onState = null }) {
  // A seeded open (from a Solutions card, the Moon CTA, a nav button) skips straight
  // past the intent step and carries the industry into the brief.
  const [step, setStep] = useState(seed?.intent ? 1 : 0)
  const [dir, setDir] = useState(1)
  const [intent, setIntent] = useState(seed?.intent ?? null)
  const [needs, setNeeds] = useState([])
  const [form, setForm] = useState({ name: '', company: '', budget: '', timeline: '', message: '' })
  const [touched, setTouched] = useState(false)

  const go = (n) => { setDir(n > step ? 1 : -1); setStep(n); onState?.(STEP_STATE[n]) }
  const toggleNeed = (n) =>
    setNeeds((xs) => (xs.includes(n) ? xs.filter((x) => x !== n) : [...xs, n]))

  // Greet on mount — a seeded open lands on step 1, so read the step, not a constant.
  useEffect(() => { onState?.(STEP_STATE[step]) }, [])

  const intentObj = WIZARD.intents.find((i) => i.id === intent)
  const brief = useMemo(() => {
    const lines = [
      `Hi LOOM! ${intentObj ? intentObj.title : ''}`.trim(),
      seed?.niche ? `Industry: ${seed.niche}` : null,
      seed?.note ? `About: ${seed.note}` : null,
      needs.length ? `What I need: ${needs.join(', ')}` : null,
      form.name ? `Name: ${form.name}` : null,
      form.company ? `Company: ${form.company}` : null,
      form.budget ? `Budget: ${form.budget}` : null,
      form.timeline ? `Timeline: ${form.timeline}` : null,
      form.message ? `Details: ${form.message}` : null,
    ].filter(Boolean)
    return lines.join('\n')
  }, [intentObj, needs, form, seed])

  const waHref = `${BRAND.whatsapp}?text=${encodeURIComponent(brief)}`
  const mailHref = `mailto:${BRAND.email}?subject=${encodeURIComponent(`Project inquiry — ${intentObj ? intentObj.title : 'LOOM'}`)}&body=${encodeURIComponent(brief)}`
  const detailsValid = form.name.trim().length > 1

  const slide = {
    initial: (d) => ({ opacity: 0, x: d * 60 }),
    animate: { opacity: 1, x: 0 },
    exit: (d) => ({ opacity: 0, x: d * -60 }),
  }

  return (
    <div className="wizard">
      {seed?.niche && (
        <div className="wizard-seed">
          Building for <strong>{seed.niche}</strong>
        </div>
      )}
      {/* A progress rail, not a tablist — the steps own no tabpanels and only
          the already-completed ones are reachable. aria-current marks where
          you are; the disabled state already says where you cannot go yet. */}
      <div className="wizard-steps" role="group" aria-label="Inquiry steps">
        {STEPS.map((s, i) => (
          <button
            key={s}
            aria-current={step === i ? 'step' : undefined}
            className={`wstep ${i === step ? 'is-now' : ''} ${i < step ? 'is-done' : ''}`}
            onClick={() => i < step && go(i)}
            disabled={i > step}
          >
            <i>{i + 1}</i>{s}
          </button>
        ))}
        <div className="wizard-bar" aria-hidden="true">
          <motion.i animate={{ scaleX: (step + 1) / STEPS.length }} transition={{ duration: 0.5, ease: EASE }} />
        </div>
      </div>

      <div className="wizard-stage">
        <AnimatePresence mode="wait" custom={dir} initial={false}>
          {step === 0 && (
            <motion.div key="s0" className="wpane" custom={dir} variants={slide}
              initial="initial" animate="animate" exit="exit" transition={{ duration: 0.45, ease: EASE }}>
              <h3 className="wq">What brings you to the loom?</h3>
              <div className="wintents">
                {WIZARD.intents.map((it) => (
                  <button
                    key={it.id}
                    className={`wintent ${intent === it.id ? 'is-picked' : ''}`}
                    onClick={() => { setIntent(it.id); go(1) }}
                  >
                    <span className="wintent-icon" aria-hidden="true">
                      <WoolIcon name={it.wool} size="lg" />
                    </span>
                    <span className="wintent-title">{it.title}</span>
                    <span className="wintent-sub">{it.sub}</span>
                  </button>
                ))}
              </div>
            </motion.div>
          )}

          {step === 1 && (
            <motion.div key="s1" className="wpane" custom={dir} variants={slide}
              initial="initial" animate="animate" exit="exit" transition={{ duration: 0.45, ease: EASE }}>
              <h3 className="wq">What do you need exactly?</h3>
              <p className="wsub">Pick everything that applies — we’ll shape it with you.</p>
              <div className="wchips">
                {WIZARD.needs.map((n) => (
                  <button
                    key={n}
                    className={`wchip ${needs.includes(n) ? 'is-on' : ''}`}
                    aria-pressed={needs.includes(n)}
                    onClick={() => toggleNeed(n)}
                  >{n}</button>
                ))}
              </div>
              {/* generic wizard chrome — the photographed Back / Next knits are the right cut here */}
              <div className="wnav">
                <WoolButton label="Back" size="small" onClick={() => go(0)} />
                <WoolButton
                  label="Next"
                  size="small"
                  disabled={!needs.length}
                  style={needs.length ? undefined : WOOL_OFF}
                  onClick={() => go(2)}
                />
              </div>
            </motion.div>
          )}

          {step === 2 && (
            <motion.div key="s2" className="wpane" custom={dir} variants={slide}
              initial="initial" animate="animate" exit="exit" transition={{ duration: 0.45, ease: EASE }}>
              <h3 className="wq">Almost there — the essentials.</h3>
              <div className="wform">
                <label>
                  <span>Your name *</span>
                  <input
                    value={form.name}
                    onChange={(e) => setForm({ ...form, name: e.target.value })}
                    // The Review button is disabled while this is empty, so it can
                    // never report the failure — blur is the only moment the visitor
                    // actually leaves the field unfilled.
                    onBlur={() => {
                      setTouched(true)
                      onState?.(detailsValid ? 'details' : 'error')
                    }}
                    placeholder="e.g. Rania Haddad"
                    aria-invalid={touched && !detailsValid}
                  />
                </label>
                <label>
                  <span>Company / project</span>
                  <input
                    value={form.company}
                    onChange={(e) => setForm({ ...form, company: e.target.value })}
                    placeholder="optional"
                  />
                </label>
                <label>
                  <span>Budget</span>
                  <select value={form.budget} onChange={(e) => setForm({ ...form, budget: e.target.value })}>
                    <option value="">Prefer not to say</option>
                    {WIZARD.budgets.map((b) => <option key={b} value={b}>{b}</option>)}
                  </select>
                </label>
                <label>
                  <span>Timeline</span>
                  <select value={form.timeline} onChange={(e) => setForm({ ...form, timeline: e.target.value })}>
                    <option value="">Not sure yet</option>
                    {WIZARD.timelines.map((t) => <option key={t} value={t}>{t}</option>)}
                  </select>
                </label>
                <label className="wfull">
                  <span>Tell us more</span>
                  <textarea
                    rows={4}
                    value={form.message}
                    onChange={(e) => setForm({ ...form, message: e.target.value })}
                    placeholder="The idea, the market, the deadline — anything that helps us think."
                  />
                </label>
              </div>
              <div className="wnav">
                <button className="wback" onClick={() => go(1)}>← Back</button>
                <WoolButton
                  label="Review"
                  size="small"
                  disabled={!detailsValid}
                  style={detailsValid ? undefined : WOOL_OFF}
                  onClick={() => { setTouched(true); if (detailsValid) go(3) }}
                />
              </div>
            </motion.div>
          )}

          {step === 3 && (
            <motion.div key="s3" className="wpane" custom={dir} variants={slide}
              initial="initial" animate="animate" exit="exit" transition={{ duration: 0.45, ease: EASE }}>
              <h3 className="wq">Your brief, woven. Send it your way.</h3>
              <pre className="wbrief" aria-label="Your inquiry summary">{brief}</pre>
              <div className="wsend">
                {/* two yarns, so the choice reads as two threads rather than
                    a primary and a leftover */}
                {/* Both hand off to another app, so 'sent' is the honest word for
                    what we know: the brief left here. */}
                <Magnetic>
                  <WoolButton label="Send via WhatsApp" size="big" href={waHref} target="_blank" rel="noreferrer"
                    onClick={() => onState?.('sent')} />
                </Magnetic>
                <Magnetic>
                  <WoolButton label="Send as email" size="big" yarn="blue" href={mailHref}
                    onClick={() => onState?.('sent')} />
                </Magnetic>
              </div>
              <div className="wnav wnav--end">
                <button className="wback" onClick={() => go(2)}>← Edit details</button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}

// src/lib/components/ContactWizard.svelte
<!--
  Multi-step contact wizard: intent -> needs -> details -> WhatsApp / email handoff.
  Fully static — composes a structured brief and opens wa.me / mailto prefilled.
-->
<script>
  import { fly } from 'svelte/transition'
  import { cubicOut } from 'svelte/easing'
  import { BRAND, WIZARD } from '$data/site.js'
  import { EASE, magnetic } from '$lib/motion.svelte.js'
  import WoolButton from './WoolButton.svelte'
  import WoolIcon from './WoolIcon.svelte'

  let { seed = null, onState = null } = $props()

  const STEPS = ['Start', 'Needs', 'Details', 'Send']
  // Which beat of the machine's script each step corresponds to. Kept here
  // rather than in the machine so the wizard stays the single source of truth
  // for where you are.
  const STEP_STATE = ['greet', 'needs', 'details', 'review']

  // A seeded open (from a Solutions card, the Moon CTA, a nav button) skips
  // straight past the intent step and carries the industry into the brief.
  let step = $state(seed?.intent ? 1 : 0)
  let dir = $state(1)
  let intent = $state(seed?.intent ?? null)
  let needs = $state([])
  let form = $state({ name: '', company: '', budget: '', timeline: '', message: '' })
  let touched = $state(false)

  function go(n) {
    dir = n > step ? 1 : -1
    step = n
    onState?.(STEP_STATE[n])
  }
  function toggleNeed(n) {
    needs = needs.includes(n) ? needs.filter((x) => x !== n) : [...needs, n]
  }

  // Greet on mount — a seeded open lands on step 1, so read the step, not a
  // constant. Runs once, at component init (the `$effect` must be called at
  // the top level, per the runes rule — an onMount-wrapped one is an orphan).
  $effect(() => { onState?.(STEP_STATE[step]) })

  const intentObj = $derived(WIZARD.intents.find((i) => i.id === intent))
  const brief = $derived(
    [
      `Hi LOOM! ${intentObj ? intentObj.title : ''}`.trim(),
      seed?.niche ? `Industry: ${seed.niche}` : null,
      seed?.note ? `About: ${seed.note}` : null,
      needs.length ? `What I need: ${needs.join(', ')}` : null,
      form.name ? `Name: ${form.name}` : null,
      form.company ? `Company: ${form.company}` : null,
      form.budget ? `Budget: ${form.budget}` : null,
      form.timeline ? `Timeline: ${form.timeline}` : null,
      form.message ? `Details: ${form.message}` : null,
    ].filter(Boolean).join('\n')
  )

  const waHref = $derived(`${BRAND.whatsapp}?text=${encodeURIComponent(brief)}`)
  const mailHref = $derived(
    `mailto:${BRAND.email}?subject=${encodeURIComponent(`Project inquiry — ${intentObj ? intentObj.title : 'LOOM'}`)}&body=${encodeURIComponent(brief)}`
  )
  const detailsValid = $derived(form.name.trim().length > 1)

  // Mirrors AnimatePresence's `initial={false}`: the very first pane the
  // wizard shows on mount must not slide/fade in — the modal shell around it
  // is already playing its own entrance, and animating this too read as two
  // entrances stacked. Every pane after that (an actual step change) still
  // gets the slide. A plain closure flag rather than state — flipping it must
  // never trigger a re-render.
  let firstPane = true
  function paneIn(node, params) {
    if (firstPane) { firstPane = false; return { duration: 0 } }
    return fly(node, params)
  }
</script>

<div class="wizard">
  {#if seed?.niche}
    <div class="wizard-seed">
      Building for <strong>{seed.niche}</strong>
    </div>
  {/if}

  <!-- A progress rail, not a tablist — the steps own no tabpanels and only
       the already-completed ones are reachable. aria-current marks where you
       are; the disabled state already says where you cannot go yet. -->
  <div class="wizard-steps" role="group" aria-label="Inquiry steps">
    {#each STEPS as s, i (s)}
      <button
        type="button"
        aria-current={step === i ? 'step' : undefined}
        class="wstep {i === step ? 'is-now' : ''} {i < step ? 'is-done' : ''}"
        onclick={() => { if (i < step) go(i) }}
        disabled={i > step}
      ><i>{i + 1}</i>{s}</button>
    {/each}
    <div class="wizard-bar" aria-hidden="true">
      <i style="transform: scaleX({(step + 1) / STEPS.length}); transition: transform 0.5s {EASE};"></i>
    </div>
  </div>

  <div class="wizard-stage">
    {#key step}
      {#if step === 0}
        <div class="wpane" in:paneIn={{ x: dir * 60, opacity: 0, duration: 450, easing: cubicOut }}
             out:fly={{ x: dir * -60, opacity: 0, duration: 450, easing: cubicOut }}>
          <h3 class="wq">What brings you to the loom?</h3>
          <div class="wintents">
            {#each WIZARD.intents as it (it.id)}
              <button
                type="button"
                class="wintent {intent === it.id ? 'is-picked' : ''}"
                onclick={() => { intent = it.id; go(1) }}
              >
                <span class="wintent-icon" aria-hidden="true">
                  <WoolIcon name={it.wool} size="lg" />
                </span>
                <span class="wintent-title">{it.title}</span>
                <span class="wintent-sub">{it.sub}</span>
              </button>
            {/each}
          </div>
        </div>
      {:else if step === 1}
        <div class="wpane" in:paneIn={{ x: dir * 60, opacity: 0, duration: 450, easing: cubicOut }}
             out:fly={{ x: dir * -60, opacity: 0, duration: 450, easing: cubicOut }}>
          <h3 class="wq">What do you need exactly?</h3>
          <p class="wsub">Pick everything that applies — we’ll shape it with you.</p>
          <div class="wchips">
            {#each WIZARD.needs as n (n)}
              <button
                type="button"
                class="wchip {needs.includes(n) ? 'is-on' : ''}"
                aria-pressed={needs.includes(n)}
                onclick={() => toggleNeed(n)}
              >{n}</button>
            {/each}
          </div>
          <!-- generic wizard chrome — the photographed Back / Next knits are the right cut here -->
          <div class="wnav">
            <WoolButton label="Back" size="small" onclick={() => go(0)} />
            <WoolButton
              label="Next"
              size="small"
              disabled={!needs.length}
              style={needs.length ? undefined : 'opacity: 0.4; pointer-events: none;'}
              onclick={() => go(2)}
            />
          </div>
        </div>
      {:else if step === 2}
        <div class="wpane" in:paneIn={{ x: dir * 60, opacity: 0, duration: 450, easing: cubicOut }}
             out:fly={{ x: dir * -60, opacity: 0, duration: 450, easing: cubicOut }}>
          <h3 class="wq">Almost there — the essentials.</h3>
          <div class="wform">
            <label>
              <span>Your name *</span>
              <input
                value={form.name}
                oninput={(e) => { form = { ...form, name: e.target.value } }}
                onblur={() => {
                  touched = true
                  onState?.(detailsValid ? 'details' : 'error')
                }}
                placeholder="e.g. Rania Haddad"
                aria-invalid={touched && !detailsValid}
              />
            </label>
            <label>
              <span>Company / project</span>
              <input
                value={form.company}
                oninput={(e) => { form = { ...form, company: e.target.value } }}
                placeholder="optional"
              />
            </label>
            <label>
              <span>Budget</span>
              <select value={form.budget} onchange={(e) => { form = { ...form, budget: e.target.value } }}>
                <option value="">Prefer not to say</option>
                {#each WIZARD.budgets as b (b)}<option value={b}>{b}</option>{/each}
              </select>
            </label>
            <label>
              <span>Timeline</span>
              <select value={form.timeline} onchange={(e) => { form = { ...form, timeline: e.target.value } }}>
                <option value="">Not sure yet</option>
                {#each WIZARD.timelines as t (t)}<option value={t}>{t}</option>{/each}
              </select>
            </label>
            <label class="wfull">
              <span>Tell us more</span>
              <textarea
                rows="4"
                value={form.message}
                oninput={(e) => { form = { ...form, message: e.target.value } }}
                placeholder="The idea, the market, the deadline — anything that helps us think."
              ></textarea>
            </label>
          </div>
          <div class="wnav">
            <button type="button" class="wback" onclick={() => go(1)}>← Back</button>
            <WoolButton
              label="Review"
              size="small"
              disabled={!detailsValid}
              style={detailsValid ? undefined : 'opacity: 0.4; pointer-events: none;'}
              onclick={() => { touched = true; if (detailsValid) go(3) }}
            />
          </div>
        </div>
      {:else if step === 3}
        <div class="wpane" in:paneIn={{ x: dir * 60, opacity: 0, duration: 450, easing: cubicOut }}
             out:fly={{ x: dir * -60, opacity: 0, duration: 450, easing: cubicOut }}>
          <h3 class="wq">Your brief, woven. Send it your way.</h3>
          <pre class="wbrief" aria-label="Your inquiry summary">{brief}</pre>
          <div class="wsend">
            <!-- two yarns, so the choice reads as two threads rather than a
                 primary and a leftover. Both hand off to another app, so
                 'sent' is the honest word for what we know: the brief left
                 here. -->
            <div use:magnetic>
              <WoolButton label="Send via WhatsApp" size="big" href={waHref} target="_blank" rel="noreferrer"
                onclick={() => onState?.('sent')} />
            </div>
            <div use:magnetic>
              <WoolButton label="Send as email" size="big" yarn="blue" href={mailHref}
                onclick={() => onState?.('sent')} />
            </div>
          </div>
          <div class="wnav wnav--end">
            <button type="button" class="wback" onclick={() => go(2)}>← Edit details</button>
          </div>
        </div>
      {/if}
    {/key}
  </div>
</div>
